name: Kompilator Purple-Clienta Fabric
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie projektu
        uses: actions/checkout@v4

      - name: Konfiguracja Javy 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Inicjalizacja srodowiska i kompilacja kodu JAR
        run: |
          gradle wrapper --gradle-version 8.11.1
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Przesylanie gotowego Purple Clienta na dysk
        uses: actions/upload-artifact@v4
        with:
          name: Purple-Client-JAR
          path: build/libs/*
